#!/bin/bash
# ═══════════════════════════════════════════════════════════════
# DIALBEE — ONE COMMAND SETUP SCRIPT
# Run this on your server to set up everything automatically
# Usage: curl -sSL https://raw.githubusercontent.com/YOUR/dialbee/main/install.sh | bash
# ═══════════════════════════════════════════════════════════════

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
BOLD='\033[1m'
NC='\033[0m'

print_step()  { echo -e "\n${BLUE}${BOLD}▶ $1${NC}"; }
print_ok()    { echo -e "${GREEN}✅ $1${NC}"; }
print_warn()  { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; exit 1; }

echo -e "
${BOLD}${BLUE}
╔══════════════════════════════════════════╗
║     🌍 DIALBEE — Auto Setup Script       ║
║     Africa & Europe Business Directory  ║
╚══════════════════════════════════════════╝
${NC}"

# ── Check OS ──────────────────────────────────────────────────
OS=$(uname -s)
print_step "Detecting operating system..."
echo "   OS: $OS"

# ── Step 1: Install Node.js ───────────────────────────────────
print_step "Installing Node.js 20..."

if command -v node &> /dev/null; then
  NODE_VER=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
  if [ "$NODE_VER" -ge 18 ]; then
    print_ok "Node.js $(node -v) already installed"
  else
    print_warn "Node.js version too old, upgrading..."
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
  fi
else
  if [ "$OS" = "Linux" ]; then
    curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
    sudo apt-get install -y nodejs
  elif [ "$OS" = "Darwin" ]; then
    if ! command -v brew &> /dev/null; then
      /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    fi
    brew install node@20
  fi
fi
print_ok "Node.js $(node -v)"

# ── Step 2: Install Docker ────────────────────────────────────
print_step "Installing Docker..."

if command -v docker &> /dev/null; then
  print_ok "Docker already installed: $(docker --version)"
else
  if [ "$OS" = "Linux" ]; then
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker $USER
    print_ok "Docker installed (you may need to logout and login)"
  else
    print_warn "Please install Docker Desktop manually: https://docker.com/get-started"
    read -p "Press Enter when Docker is installed..."
  fi
fi

# Docker Compose check
if ! command -v docker-compose &> /dev/null && ! docker compose version &> /dev/null 2>&1; then
  sudo apt-get install -y docker-compose-plugin
fi
print_ok "Docker Compose available"

# ── Step 3: Install PM2 (process manager) ────────────────────
print_step "Installing PM2..."
if ! command -v pm2 &> /dev/null; then
  sudo npm install -g pm2
fi
print_ok "PM2 $(pm2 --version)"

# ── Step 4: Install Nginx ─────────────────────────────────────
if [ "$OS" = "Linux" ]; then
  print_step "Installing Nginx..."
  if ! command -v nginx &> /dev/null; then
    sudo apt-get install -y nginx
    sudo systemctl enable nginx
    sudo systemctl start nginx
  fi
  print_ok "Nginx installed"
fi

# ── Step 5: Setup Project ─────────────────────────────────────
print_step "Setting up project..."

# Ask for domain
echo ""
echo -e "${BOLD}Configuration:${NC}"
read -p "Enter your domain (e.g. yourdomain.com): " DOMAIN
read -p "Enter your admin email: " ADMIN_EMAIL
read -p "Enter JWT secret (any 32+ char random string): " JWT_SECRET

if [ -z "$DOMAIN" ] || [ -z "$ADMIN_EMAIL" ]; then
  print_error "Domain and admin email are required!"
fi

# Generate a random JWT if not provided
if [ -z "$JWT_SECRET" ]; then
  JWT_SECRET=$(openssl rand -base64 32)
  echo "Generated JWT Secret: $JWT_SECRET"
fi

# ── Step 6: Create .env files ─────────────────────────────────
print_step "Creating environment files..."

cat > backend/.env << EOF
# Generated by Dialbee setup script
NODE_ENV=production
PORT=3001
APP_URL=https://api.$DOMAIN
FRONTEND_URL=https://$DOMAIN

DATABASE_URL=postgresql://dialbee:dialbee_pass_2024@localhost:5432/dialbee
REDIS_URL=redis://:dialbee_redis_2024@localhost:6379
ELASTICSEARCH_URL=http://localhost:9200

JWT_ACCESS_SECRET=$JWT_SECRET
JWT_REFRESH_SECRET=${JWT_SECRET}_refresh
JWT_ACCESS_EXPIRES=15m
JWT_REFRESH_EXPIRES=30d

SMTP_HOST=localhost
SMTP_PORT=1025
EMAIL_FROM=noreply@$DOMAIN

# REPLACE WITH YOUR KEYS:
STRIPE_SECRET_KEY=sk_test_REPLACE_ME
STRIPE_WEBHOOK_SECRET=whsec_REPLACE_ME
PAYSTACK_SECRET_KEY=sk_test_REPLACE_ME

ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=Admin@Dialbee2024!
EOF

cat > frontend/.env.local << EOF
NEXT_PUBLIC_API_URL=https://api.$DOMAIN
NEXT_PUBLIC_APP_URL=https://$DOMAIN
EOF

print_ok "Environment files created"

# ── Step 7: Start Docker services ────────────────────────────
print_step "Starting database services..."
docker-compose up -d postgres redis elasticsearch mailhog

echo "   Waiting for services to start (30 seconds)..."
sleep 30

# Health checks
echo -n "   PostgreSQL: "
if docker exec dialbee_postgres pg_isready -U dialbee 2>/dev/null; then
  echo -e "${GREEN}✅${NC}"
else
  print_warn "PostgreSQL not ready yet, continuing..."
fi

echo -n "   Redis: "
if docker exec dialbee_redis redis-cli ping 2>/dev/null | grep -q PONG; then
  echo -e "${GREEN}✅${NC}"
else
  print_warn "Redis not ready yet, continuing..."
fi

# ── Step 8: Install dependencies ─────────────────────────────
print_step "Installing backend dependencies..."
cd backend
npm install --production
npm run build
print_ok "Backend built"

print_step "Installing frontend dependencies..."
cd ../frontend
npm install
npm run build
print_ok "Frontend built"
cd ..

# ── Step 9: Start with PM2 ────────────────────────────────────
print_step "Starting application with PM2..."

pm2 delete dialbee-api 2>/dev/null || true
pm2 delete dialbee-web 2>/dev/null || true

cd backend
pm2 start "npm run start:prod" \
  --name dialbee-api \
  --env production \
  --max-memory-restart 500M \
  --restart-delay 3000

cd ../frontend
pm2 start "npm run start" \
  --name dialbee-web \
  --env production \
  --max-memory-restart 400M

pm2 save
pm2 startup | tail -1 | sudo bash 2>/dev/null || true

cd ..
print_ok "Application started with PM2"

# ── Step 10: Configure Nginx ──────────────────────────────────
if [ "$OS" = "Linux" ]; then
  print_step "Configuring Nginx..."

  sudo tee /etc/nginx/sites-available/dialbee > /dev/null << EOF
# Dialbee - API
server {
    listen 80;
    server_name api.$DOMAIN;

    client_max_body_size 50M;

    location / {
        proxy_pass http://localhost:3001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_cache_bypass \$http_upgrade;
        proxy_read_timeout 60s;
    }
}

# Dialbee - Frontend
server {
    listen 80;
    server_name $DOMAIN www.$DOMAIN;

    location / {
        proxy_pass http://localhost:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_cache_bypass \$http_upgrade;
    }

    # Cache static files
    location /_next/static/ {
        proxy_pass http://localhost:3000;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
EOF

  sudo ln -sf /etc/nginx/sites-available/dialbee /etc/nginx/sites-enabled/dialbee
  sudo rm -f /etc/nginx/sites-enabled/default
  sudo nginx -t && sudo systemctl reload nginx
  print_ok "Nginx configured"

  # ── Step 11: SSL Certificate ──────────────────────────────
  print_step "Installing SSL certificate..."

  if ! command -v certbot &> /dev/null; then
    sudo apt-get install -y certbot python3-certbot-nginx
  fi

  echo ""
  print_warn "DNS must be pointing to this server before SSL installation."
  read -p "Is DNS configured? (y/n): " DNS_READY

  if [ "$DNS_READY" = "y" ] || [ "$DNS_READY" = "Y" ]; then
    sudo certbot --nginx \
      -d $DOMAIN \
      -d www.$DOMAIN \
      -d api.$DOMAIN \
      --non-interactive \
      --agree-tos \
      --email $ADMIN_EMAIL \
      --redirect

    # Auto-renewal
    (crontab -l 2>/dev/null; echo "0 12 * * * /usr/bin/certbot renew --quiet") | crontab -
    print_ok "SSL certificate installed"
  else
    print_warn "Skipping SSL. Run 'sudo certbot --nginx -d $DOMAIN -d api.$DOMAIN' when DNS is ready."
  fi
fi

# ── Step 12: Elasticsearch index ─────────────────────────────
print_step "Creating Elasticsearch index..."

sleep 10

curl -s -X PUT "http://localhost:9200/businesses_v1" \
  -H "Content-Type: application/json" \
  -d '{
    "settings": {
      "number_of_shards": 1,
      "number_of_replicas": 0
    },
    "mappings": {
      "properties": {
        "id":                 { "type": "keyword" },
        "name":               { "type": "text", "boost": 4 },
        "category_name":      { "type": "text", "boost": 3 },
        "city":               { "type": "keyword" },
        "country_code":       { "type": "keyword" },
        "location":           { "type": "geo_point" },
        "avg_rating":         { "type": "float" },
        "total_reviews":      { "type": "integer" },
        "subscription_tier":  { "type": "keyword" },
        "is_active":          { "type": "boolean" },
        "ai_quality_score":   { "type": "float" }
      }
    }
  }' > /dev/null 2>&1 && print_ok "Elasticsearch index created" || print_warn "ES index creation skipped"

# ── Final Summary ─────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}
╔══════════════════════════════════════════════════════════╗
║  🎉 DIALBEE IS LIVE!                                      ║
╠══════════════════════════════════════════════════════════╣
║                                                          ║
║  🌐 Website:   https://$DOMAIN
║  🔌 API:       https://api.$DOMAIN/api/docs
║  📧 Email UI:  http://localhost:8025 (dev only)          ║
║                                                          ║
║  Admin Login:                                            ║
║    Email:    $ADMIN_EMAIL
║    Password: Admin@Dialbee2024!                           ║
║                                                          ║
║  ⚠️  NEXT STEPS:                                         ║
║  1. Add Stripe keys to backend/.env                      ║
║  2. Add Paystack keys to backend/.env                    ║
║  3. Add 50+ businesses via admin panel                   ║
║  4. Start WhatsApp marketing!                            ║
║                                                          ║
╚══════════════════════════════════════════════════════════╝
${NC}"

echo "PM2 Status:"
pm2 status
